Create CONTRIBUTING.md
conjurinc/debify pull request #38
Opened 2020-03-11 19:19 UTC by BradleyBoutcher

2020-03-11 21:41 UTC, izgeri requested changes
The TOC can be removed, and the README contributing info should be removed in favor of linking here

2020-03-25 14:03 UTC, jtuttle commented
@BradleyBoutcher Got time to merge this down soon? Looks like a pretty simple change needed to get it mergeable.

2020-04-06 21:15 UTC, izgeri requested changes
still outstanding on this PR:
- [ ] Update the bottom of the README to link to CONTRIBUTING.md instead of repeating its content.

2020-04-15 14:28 UTC, izgeri approved these changes

2020-04-15 14:31 UTC, merged